CREATE DATABASE IF NOT EXISTS pos;

CREATE TABLE IF NOT EXISTS productos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    precio DECIMAL(10, 2) NOT NULL,
    descripcion TEXT,
    imagen VARCHAR(255)
);

INSERT INTO productos (nombre, precio, descripcion, imagen) VALUES
('Camiseta', 19.99, 'Camiseta de algodón de alta calidad', 'camiseta.jpg'),
('Pantalones', 39.99, 'Pantalones vaqueros cómodos y duraderos', 'pantalones.jpg'),
('Zapatos', 59.99, 'Zapatos deportivos para todas las actividades', 'zapatos.jpg'),
('Chaqueta', 89.99, 'Chaqueta impermeable para todas las estaciones', 'chaqueta.jpg'),
('Sombrero', 14.99, 'Sombrero elegante para cualquier ocasión', 'sombrero.jpg'),
('Bufanda', 12.99, 'Bufanda de lana suave y cálida', 'bufanda.jpg'),
('Guantes', 9.99, 'Guantes resistentes al frío', 'guantes.jpg'),
('Reloj', 199.99, 'Reloj de pulsera moderno y funcional', 'reloj.jpg'),
('Mochila', 49.99, 'Mochila espaciosa para uso diario', 'mochila.jpg'),
('Gafas de sol', 29.99, 'Gafas de sol con protección UV', 'gafas.jpg'),
('Cinturón', 24.99, 'Cinturón de cuero genuino', 'cinturon.jpg'),
('Calcetines', 7.99, 'Calcetines cómodos y transpirables', 'calcetines.jpg'),
('Camisa', 34.99, 'Camisa formal para ocasiones especiales', 'camisa.jpg'),
('Falda', 44.99, 'Falda elegante para eventos sociales', 'falda.jpg'),
('Vestido', 59.99, 'Vestido casual para el día a día', 'vestido.jpg'),
('Traje de baño', 29.99, 'Traje de baño para disfrutar del verano', 'traje_bano.jpg'),
('Toalla', 19.99, 'Toalla suave y absorbente', 'toalla.jpg'),
('Almohada', 39.99, 'Almohada ergonómica para un buen descanso', 'almohada.jpg'),
('Sábana', 49.99, 'Juego de sábanas de alta calidad', 'sabana.jpg'),
('Manta', 59.99, 'Manta cálida para las noches frías', 'manta.jpg'),
('Lámpara', 79.99, 'Lámpara de mesa moderna', 'lampara.jpg'),
('Espejo', 89.99, 'Espejo decorativo para el hogar', 'espejo.jpg'),
('Cuadro', 99.99, 'Cuadro artístico para decorar paredes', 'cuadro.jpg'),
('Jarrón', 29.99, 'Jarrón elegante para flores', 'jarron.jpg'),
('Reloj de pared', 49.99, 'Reloj de pared clásico', 'reloj_pared.jpg'),
('Silla', 149.99, 'Silla ergonómica para oficina', 'silla.jpg'),
('Mesa', 199.99, 'Mesa de comedor moderna', 'mesa.jpg'),
('Estantería', 129.99, 'Estantería para libros y decoración', 'estanteria.jpg'),
('Alfombra', 89.99, 'Alfombra suave para el salón', 'alfombra.jpg'),
('Cortina', 59.99, 'Cortina opaca para ventanas', 'cortina.jpg'),
('Televisor', 499.99, 'Televisor LED de alta definición', 'televisor.jpg'),
('Equipo de sonido', 299.99, 'Sistema de sonido envolvente', 'equipo_sonido.jpg'),
('Auriculares', 79.99, 'Auriculares inalámbricos con cancelación de ruido', 'auriculares.jpg'),
('Altavoz Bluetooth', 49.99, 'Altavoz portátil con Bluetooth', 'altavoz_bluetooth.jpg'),
('Cámara digital', 399.99, 'Cámara digital de alta resolución', 'camara_digital.jpg'),
('Impresora', 149.99, 'Impresora multifunción para oficina', 'impresora.jpg'),
('Portátil', 899.99, 'Portátil potente para trabajo y ocio', 'portatil.jpg'),
('Tablet', 299.99, 'Tablet ligera y versátil', 'tablet.jpg'),
('Smartphone', 699.99, 'Smartphone de última generación', 'smartphone.jpg'),
('Router WiFi', 79.99, 'Router WiFi de alta velocidad', 'router_wifi.jpg'),
('Disco duro externo', 119.99, 'Disco duro externo para almacenamiento adicional', 'disco_duro_externo.jpg'),
('Memoria USB', 19.99, 'Memoria USB de 64GB', 'memoria_usb.jpg'),
('Cargador portátil', 29.99, 'Cargador portátil para dispositivos móviles', 'cargador_portatil.jpg'),
('Teclado', 49.99, 'Teclado mecánico para gaming', 'teclado.jpg'),
('Ratón', 39.99, 'Ratón ergonómico para oficina', 'raton.jpg'),
('Monitor', 199.99, 'Monitor Full HD para trabajo y entretenimiento', 'monitor.jpg'),
('Silla de gaming', 249.99, 'Silla de gaming cómoda y ajustable', 'silla_gaming.jpg'),
('Mesa de escritorio', 179.99, 'Mesa de escritorio moderna y funcional', 'mesa_escritorio.jpg'),
('Lámpara de pie', 69.99, 'Lámpara de pie con luz regulable', 'lampara_pie.jpg'),
('Reloj inteligente', 199.99, 'Reloj inteligente con múltiples funciones', 'reloj_inteligente.jpg'),
('Pulsera de actividad', 99.99, 'Pulsera de actividad para monitorizar el ejercicio', 'pulsera_actividad.jpg'),
('Cámara de seguridad', 149.99, 'Cámara de seguridad para el hogar', 'camara_seguridad.jpg'),
('Termostato inteligente', 129.99, 'Termostato inteligente para controlar la temperatura', 'termostato_inteligente.jpg'),
('Bombilla inteligente', 29.99, 'Bombilla inteligente con control por voz', 'bombilla_inteligente.jpg'),
('Enchufe inteligente', 39.99, 'Enchufe inteligente para controlar dispositivos eléctricos', 'enchufe_inteligente.jpg'),
('Robot aspirador', 299.99, 'Robot aspirador para limpieza automática del hogar', 'robot_aspirador.jpg'),
('Cafetera', 89.99, 'Cafetera automática para café fresco', 'cafetera.jpg'),
('Tostadora', 49.99, 'Tostadora de pan con múltiples funciones', 'tostadora.jpg'),
('Microondas', 129.99, 'Microondas compacto para cocina rápida', 'microondas.jpg'),
('Horno eléctrico', 199.99, 'Horno eléctrico para cocinar y hornear', 'horno_electrico.jpg'),
('Refrigerador', 599.99, 'Refrigerador de alta capacidad y eficiencia energética', 'refrigerador.jpg'),
('Lavadora', 499.99, 'Lavadora automática con múltiples programas', 'lavadora.jpg'),
('Secadora', 399.99, 'Secadora eficiente para ropa rápida y fácil', 'secadora.jpg'),
('Aspiradora', 149.99, 'Aspiradora potente para limpieza profunda', 'aspiradora.jpg'),
('Plancha', 39.99, 'Plancha de vapor para ropa sin arrugas', 'plancha.jpg'),
('Tabla de planchar', 59.99, 'Tabla de planchar ajustable y resistente', 'tabla_planchar.jpg'),
('Ventilador', 49.99, 'Ventilador de pie para refrescar el ambiente', 'ventilador.jpg'),
('Calefactor', 69.99, 'Calefactor eléctrico para el invierno', 'calefactor.jpg'),
('Humidificador', 39.99, 'Humidificador para mejorar la calidad del aire', 'humidificador.jpg'),
('Deshumidificador', 89.99, 'Deshumidificador para eliminar la humedad del ambiente', 'deshumidificador.jpg'),
('Purificador de aire', 129.99, 'Purificador de aire para un ambiente saludable', 'purificador_aire.jpg'),
('Cortacésped', 199.99, 'Cortacésped eléctrico para mantener el jardín', 'cortacesped.jpg'),
('Manguera de jardín', 29.99, 'Manguera de jardín resistente y flexible', 'manguera_jardin.jpg'),
('Tijeras de podar', 19.99, 'Tijeras de podar para jardinería precisa', 'tijeras_podar.jpg'),
('Guantes de jardinería', 14.99, 'Guantes resistentes para jardinería', 'guantes_jardineria.jpg'),
('Regadera', 24.99, 'Regadera de metal para plantas', 'regadera.jpg'),
('Maceta', 19.99, 'Maceta decorativa para interiores y exteriores', 'maceta.jpg'),
('Fertilizante', 14.99, 'Fertilizante orgánico para plantas saludables', 'fertilizante.jpg'),
('Semillas de flores', 9.99, 'Semillas de flores variadas para jardín', 'semillas_flores.jpg'),
('Semillas de vegetales', 9.99, 'Semillas de vegetales frescos para huerto', 'semillas_vegetales.jpg'),
('Compostador', 79.99, 'Compostador para residuos orgánicos', 'compostador.jpg'),
('Banco de jardín', 149.99, 'Banco de jardín de madera resistente', 'banco_jardin.jpg'),
('Mesa de picnic', 199.99, 'Mesa de picnic plegable para exteriores', 'mesa_picnic.jpg'),
('Toldo', 129.99, 'Toldo retráctil para sombra en el jardín', 'toldo.jpg'),
('Barbacoa', 249.99, 'Barbacoa de gas para asados al aire libre', 'barbacoa.jpg'),
('Silla plegable', 39.99, 'Silla plegable para camping y exteriores', 'silla_plegable.jpg'),
('Linterna', 29.99, 'Linterna LED potente para actividades al aire libre', 'linterna.jpg'),
('Mochila de senderismo', 89.99, 'Mochila resistente para senderismo y excursiones', 'mochila_senderismo.jpg'),
('Botella de agua', 19.99, 'Botella de agua reutilizable y aislante', 'botella_agua.jpg'),
('Mapa topográfico', 14.99, 'Mapa topográfico detallado para senderismo', 'mapa_topografico.jpg'),
('Brújula', 24.99, 'Brújula precisa para orientación al aire libre', 'brujula.jpg'),
('Saco de dormir', 79.99, 'Saco de dormir cómodo y cálido para camping', 'saco_dormir.jpg'),
('Tienda de campaña', 199.99, 'Tienda de campaña espaciosa para varias personas', 'tienda_campana.jpg'),
('Colchón inflable', 59.99, 'Colchón inflable para camping y visitas', 'colchon_inflable.jpg'),
('Cocina portátil', 99.99, 'Cocina portátil para cocinar al aire libre', 'cocina_portatil.jpg'),
('Set de utensilios de cocina', 49.99, 'Set de utensilios de cocina para camping', 'set_utensilios_cocina.jpg'),
('Kit de primeros auxilios', 29.99, 'Kit de primeros auxilios completo para emergencias', 'kit_primeros_auxilios.jpg'),
('Spray repelente de insectos', 14.99, 'Spray repelente para protegerse de insectos', 'spray_repelente_insectos.jpg'),
('Protector solar', 19.99, 'Protector solar de alta protección', 'protector_solar.jpg'),
('Gafas de natación', 24.99, 'Gafas de natación con ajuste cómodo', 'gafas_natacion.jpg');